//
// Created by ukio on 22.12.2020.
//

#ifndef IMGUI_SFML_APPLICATION_UNIVERSALSUBSCRIBER_H
#define IMGUI_SFML_APPLICATION_UNIVERSALSUBSCRIBER_H




#endif //IMGUI_SFML_APPLICATION_UNIVERSALSUBSCRIBER_H
